FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y curl git build-essential sudo

# Install Homebrew
RUN useradd -m brew && echo "brew ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER brew
ENV HOME=/home/brew
ENV NONINTERACTIVE=1
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
ENV PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:${PATH}"

# Tap and install your formula
RUN brew tap aditya-baindur/quickfind && \
    brew install quickfind

CMD ["/bin/bash"]


